yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAutrhorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/card.html
{% load thumbnail %}
{% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a
          href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a
      href="{% url 'posts:post_detail' post.pk %}">
      подробная информация
    </a>
  </article>
  {% if post.group %}
    <a
      href="{% url 'posts:group_list' post.group.slug %}">
      все записи группы
    </a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3 p-3"
    {% if field.field.required %}
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control'}}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help"
        class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static  %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link
            {% if view_name == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}"
          >Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}"
          >Технологии
          </a>
        </li>
        {% if  user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'posts:post_create' %}
                active
              {% endif %}"
              href="{% url 'posts:post_create' %}"
            >Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'users:password_change_form' %}
                active
              {% endif %}
              link-light"
              href="{% url 'users:password_change_form' %}"
            >Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'users:logout' %}
                active
              {% endif %}
              link-light"
              href="{% url 'users:logout' %}"
            >Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'users:login' %}
                active
              {% endif %}
              link-light"
              href="{% url 'users:login' %}"
            >Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'users:signup' %}
                active
              {% endif %}
              link-light"
              href="{% url 'users:signup' %}"
            >Регистрация
            </a>
          </li>
        {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/users_error.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}