yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAutrhorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from posts.validators import validate_not_empty


User = get_user_model()
TEXT_LENGTH = 15


class Group(models.Model):
    """Stores groups"""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return str(self.title)


class Post(models.Model):
    """
    Stores posts, related to :model:'posts.Group'
    and :model:'posts.User'.
    """

    text = models.TextField(validators=[validate_not_empty])
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="posts",
        null=True,
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        "Картинка",
        upload_to="posts/",
        blank=True,
    )

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self) -> str:
        return str(self.text[:TEXT_LENGTH])


class Comment(models.Model):
    """
    Stores comments, related to :model:'posts.User'
    and :model:'posts.Post'.
    """

    text = models.TextField(validators=[validate_not_empty])
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        null=True,
    )


class Follow(models.Model):
    """
    Stores follow, a relatinship between :model:'posts.User'
    as authorised user and :model:'posts.User' as
    :model:'posts.Post' instance author.
    """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
    )

yatube/posts/forms.py
from django.forms import ModelForm

from posts.models import Post, Comment


class PostForm(ModelForm):
    """
    Shapes a form related to
    :model:'posts.Post'.
    """

    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )
        labels = {
            "text": "Текст поста",
            "group": "Group",
            "image": "Picture",
        }
        help_texts = {
            "text": "Текст нового поста",
            "group": "Выберите группу",
            "image": "Добавьте картинку",
        }


class CommentForm(ModelForm):
    """
    Shapes a form related to
    :model:'posts.Comment'.
    """

    class Meta:
        model = Comment
        fields = ("text",)
        labels = {
            "text": "Текст комментария",
        }
        help_texts = {
            "text": "Текст нового комментария",
        }

yatube/posts/views.py
import operator

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from posts.models import Follow, Post, Group
from posts.forms import PostForm, CommentForm


POSTS_ON_PAGE: int = 10
User = get_user_model()
CACHE_PERIOD = 20


@cache_page(CACHE_PERIOD, key_prefix="index_page")
def index(request):
    """
    Displays a paginated amount of
    :model:'posts.Post' instances.
    **Context**
    An instances of :model:'posts.Post'.
    INDEX variable related to :tag:'if', change display to
    :view:'posts.follow_index'.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'year', :tag:'thumbnail',
    :tag:'extends', :tag:'block', :tag:'url', :tag:'if',
    :tag:'date', :tag:'for', :tag:'with'
    **Template**
    :template:'posts/index.html'
    """
    INDEX: int = 1

    posts = Post.objects.select_related("author", "group")
    page_obj = paginator(posts, request)
    context = {
        "page_obj": page_obj,
        "index": INDEX,
    }
    template = "posts/index.html"
    return render(request, template, context)


def group_posts(request, slug):
    """
    Displays a paginated amount of
    :model:'posts.Post' instances,
    related to single :model:'posts.Group' instance.
    **Context**
    An instances of :model:'posts.Post' & :model:'posts.Group'.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'year', :tag:'thumbnail',
    :tag:'extends', :tag:'block', :tag:'url', :tag:'if',
    :tag:'date', :tag:'for', :tag:'with'
    **Template**
    :template:'posts/group_list.html'
    """
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("group")
    page_obj = paginator(posts, request)
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    template = "posts/group_list.html"
    return render(request, template, context)


def profile(request, username):
    """
    Displays a paginated amount of
    :model:'posts.Post' instances, where the author is
    the specific :model:'posts.User'. Allows creating and deleting
    :model:'posts.Follow' instances.
    **Context**
    An instance of :model:'posts.User' and related
    instances of :model:'posts.Post'. Also contains
    the variable 'following' to act on :model:'posts.Follow'
    instance.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'year', :tag:'thumbnail',
    :tag:'extends', :tag:'block', :tag:'url', :tag:'if',
    :tag:'date', :tag:'for', :tag:'with'
    **Template**
    :template:'posts/profile.html'
    """
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related("group")
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user, author=author)
    else:
        following = False
    page_obj = paginator(posts, request)
    context = {
        "page_obj": page_obj,
        "author": author,
        "following": following,
    }
    template = "posts/profile.html"
    return render(request, template, context)


def post_detail(request, post_id):
    """
    Displays an individual :model:'posts.Post', the amount of
    :model:'posts.Comment' & related comment form.
    **Context**
    An instances of
    :model:'posts.Post', 'posts.Comment'
    **Template tags**
    :tag:'load', :tag:'include', :tag:'extends', :tag:'block',
    :tag:'url', :tag:'if', :tag:'date', :tag:'for',
    :tag:'csrf_token', :tag:'with', :tag:'year', :tag:'thumbnail',
    **Template filters**
    :filter:'truncatechars', :filter:'addclass'
    **Template**
    :template:'posts/post_detail.html'
    """
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related("author", "post")
    form = CommentForm(request.POST or None)
    if form.is_valid():
        return redirect("posts/<int:post_id>/comment/", post_id=post_id)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    template = "posts/post_detail.html"
    return render(request, template, context)


@login_required
def post_create(request):
    """
    Displays a form, related to :model:'posts.Post'.
    For authorised users only, otherwise redirects to login url.
    **Context**
    A form to create an instance of
    :model:'posts.Post'.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'extends', :tag:'block',
    :tag:'url', :tag:'if', :tag:'for', :tag:'csrf_token',
    :tag:'with', :tag:'year'
    **Template filters**
    :filter:'addclass'
    **Template**
    :template:'posts/create_post.html'
    """
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, "posts/create_post.html", {"form": form})
    create_post = form.save(commit=False)
    create_post.author = request.user
    create_post.save()
    return redirect("posts:profile", username=request.user)


@login_required
def post_edit(request, post_id):
    """
    Displays a form, related to :model:'posts.Post'.
    For authorised users only, otherwise redirects to login url.
    **Context**
    A form to edit an instance of
    :model:'posts.Post'.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'extends', :tag:'block',
    :tag:'url', :tag:'if', :tag:'for', :tag:'csrf_token',
    :tag:'with', :tag:'year'
    **Template filters**
    :filter:'addclass'
    **Template**
    :template:'posts/create_post.html'
    """
    IS_EDIT: int = 1

    post = Post.objects.get(pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    author = post.author
    if author != request.user:
        return redirect("posts:post_detail", post_id=post_id)
    if not form.is_valid():
        return render(
            request,
            "posts/create_post.html",
            {
                "form": form,
                "is_edit": IS_EDIT,
            },
        )
    form.save()
    return redirect("posts:post_detail", post_id=post_id)


def paginator(posts, request):
    """Paginate :model:'posts.Post' instances display."""
    paginator = Paginator(posts, POSTS_ON_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return page_obj


@login_required
def add_comment(request, post_id):
    """
    Displays a form, related to :model:'posts.Comment'.
    Creates related instance.
    For authorised users only, otherwise redirects to login url.
    """
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    """
    Displays a paginated amount of
    :model:'posts.Post' instances.
    **Context**
    An instances of :model:'posts.Post'.
    FOLLOW variable related to :tag:'if', change display to
    :view:'posts.index'.
    **Template tags**
    :tag:'load', :tag:'include', :tag:'year', :tag:'thumbnail',
    :tag:'extends', :tag:'block', :tag:'url', :tag:'if',
    :tag:'date', :tag:'for', :tag:'with'
    **Template**
    :template:'posts/follow.html'
    """
    FOLLOW: int = 1

    user = request.user
    follows = Follow.objects.filter(user=user)
    posts = []
    for follow in follows:
        posts += follow.author.posts.select_related("author", "group")
    posts.sort(key=operator.attrgetter("pub_date"), reverse=True)
    page_obj = paginator(posts, request)
    context = {
        "page_obj": page_obj,
        "follow": FOLLOW,
    }
    template = "posts/follow.html"
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """
    Creates :model:'posts.Follow' instance.
    For authorised users only, otherwise redirects to login url.
    """
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    """
    Deletes :model:'posts.Follow' instance.
    For authorised users only, otherwise redirects to login url.
    """
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/users_error.html' %}
          <form method="post" enctype="multipart/form-data"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления зафолловеренных авторов
{% endblock %}
{% block content %}
  <h1>
    Последние обновления зафолловеренных авторов
  </h1>
  {% include 'posts/includes/switcher.html' %}
  {% include 'includes/card.html' %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% comment %}
    Ниже (в group_list и в includes/card) тег цикла 
    дублируется осознанно - это нужно, чтобы пройти пайтест,
    не нарушая порядок шаблонизации, предусмотренный
    с учетом ревью на предыдущую хомворк.
    Рассчитываю дублирование удалить 
    после сдачи финального проекта спринта.
  {% endcomment %}
  {% for post in page_obj %}
    {% include 'includes/card.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <h1>
    Последние обновления на сайте
  </h1>
  {% include 'posts/includes/switcher.html' %}
  {% include 'includes/card.html' %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <p>
              <a
                href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </p>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
  </div>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
      редактировать запись
    </a>
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          {% include 'includes/users_error.html' %}
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </article>  
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <article>
      <ul>
        <li>
          Автор: {{ author.get_full_name }}
          <a
            href="{% url 'posts:profile' author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </article>
    <hr>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  </div>
  {% include 'includes/card.html' %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}